Repository codestates-seb/seb44_main_002, pull requests merged in 2023-07, with the labels that each got.

#66 feat : header css 기초 틀 완성
  client/src/components/Header.js
Labels: FE, 상

#67 Feat/fe/slider
  client/package-lock.json
  client/package.json
  client/src/components/Slider.css
  client/src/components/Slider.js
  client/src/pages/Main.js
Labels: FE, 상

#70 Feat/fe/button
  client/.eslintrc.json
  client/src/common/Buttons/ClickButton.js
  client/src/common/Buttons/HoverButton.js
  client/src/common/static.js
Labels: FE, Feat

#71 Feat/fe/mainpage
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/common/Buttons/ClickButton.js
  client/src/common/Buttons/HoverButton.js
  client/src/common/static.js
  client/src/components/Header.js
  client/src/components/Slider.js
  client/src/components/Slider/Slider.css
  client/src/components/Slider/Slider.js
  client/src/pages/Main.js
  client/tailwind.config.js
Labels: FE, Feat, 상

#83 feat : headerModal 틀 완성
  client/src/components/Modal/HeaderModal.js
Labels: FE, Feat

#85 feat : hamburger 틀 완성
  client/src/components/Hamburger/Hamburger.js
Labels: FE, Feat

#87 fixed : 햄버거 드롭다운 768Px이 넘어가면 사라지게 변경
  client/src/components/Hamburger/Hamburger.js
Labels: FE, Fix

#89 Feat/fe/mainpage
  client/src/components/Hamburger/Hamburger.js
  client/src/components/Header.js
  client/src/components/Modal/HeaderModal.js
Labels: FE, Feat

#91 Chore/css reset
  client/src/App.css
  client/tailwind.config.js
Labels: FE

#96 Feat/fe/header
  client/.eslintrc.json
  client/src/components/Hamburger/Hamburger.js
  client/src/components/Header.js
  client/src/components/Modal/HeaderModal.js
  client/src/redux/index.js
  client/src/redux/slice/isLoginSlice.js
Labels: FE, Feat, 상

#99 Feat/fe/mainpage
  client/public/images/슬라이더샘플.jpg
  client/public/images/슬라이더샘플2.jpg
  client/src/components/Hamburger/Hamburger.js
  client/src/components/Header.js
  client/src/components/Slider/Slider.js
  client/src/pages/Main.js
Labels: FE, Feat

#100 Feat/fe/sortfilter
  client/.eslintrc.json
  client/public/images/background/music-dynamic-gradient.png
  client/public/images/background/star-dynamic-gradient.png
  client/public/images/bookmark/bookmarkOff.png
  client/public/images/bookmark/bookmarkOn.png
  client/src/App.js
  client/src/common/Data/index.js
  client/src/components/BookmarkButton/BookmarkButton.js
  client/src/pages/Category/Category.js
  client/src/pages/Category/Filter.js
  client/src/pages/Category/Sort.js
  client/src/pages/Category/SortConditionButton.js
  client/src/pages/CocktailForm.js
Labels: FE, Feat

#105 feat : 별점 1~5위 칵테일 더미데이터로 작업완료
  client/src/components/Ranking/Ranking.js
  client/src/pages/Main.js
Labels: FE, Feat

#108 Feat/fe/mainpage
  client/src/components/Hamburger/Hamburger.js
  client/src/components/Header.js
  client/src/components/Modal/HeaderModal.js
  client/src/components/Slider/Slider.css
  client/src/components/Slider/Slider.js
Labels: FE, Feat

#109 fixed : 스와이퍼 안보이던 버그 해결
  client/src/components/Slider/Slider.js
Labels: FE, Fix

#114 Feat/fe/mainpage
  client/src/components/Advice/Advice.js
  client/src/pages/Main.js
Labels: FE, Feat

#116 Feat/fe/mainpage
  client/src/components/Footer.js
Labels: FE, Feat, 하

#117 feat : login 기본틀 구현 & 유효성 검사 구현
  client/src/components/Input/Input.js
  client/src/components/Modal/HeaderModal.js
  client/src/components/Validation/Validation.js
Labels: FE, Feat

#120 feat: detail 페이지 1차 완성
  client/public/images/bookmark.png
  client/public/images/bookmark_selected.png
  client/public/images/star.png
  client/public/images/star_selected.png
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/Process.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
  client/src/pages/RecipeDetail/Recommend.js
  client/tailwind.config.js
Labels: FE, Feat, 상

#121 chore : 웹사이트 파비콘 변경 및 타이틀 변경
  client/public/favicon.ico
  client/public/index.html
Labels: FE, 하

#129 Feat/fe/signup
  client/public/images/background/pencil.png
  client/src/App.js
  client/src/components/Input/Input.js
  client/src/pages/Signup.js
Labels: FE, Feat, 상

#130 feat : 로그인 유효성 검사, 회원가입 유효성 검사 로직 분리
  client/src/components/Modal/HeaderModal.js
  client/src/components/Validation/LoginValidation.js
  client/src/components/Validation/SignupValidation.js
  client/src/pages/Signup.js
Labels: FE, Feat

#132 파일구조 정리
  client/src/App.js
  client/src/components/Header/Hamburger.js
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Community/Community.js
  client/src/pages/Community/CommunityDetail.js
  client/src/pages/Community/CreatePost.js
  client/src/pages/Community/ModifyComments.js
  client/src/pages/Community/ModifyPost.js
  client/src/pages/Main/Advice/Advice.js
  client/src/pages/Main/Main.js
  client/src/pages/Main/Ranking/Ranking.js
  client/src/pages/Main/Slider/Slider.css
  client/src/pages/Main/Slider/Slider.js
  client/src/pages/Mypage/Mypage.js
  client/src/pages/User/Login.js
  client/src/pages/User/Signup.js
Labels: FE, Chore

#133 feat: 댓글 유효성 검사
  client/src/components/Validation/CommentValidation.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/Recommend.js
Labels: FE, 상

#146 Feat/fe/cocktailform
  client/public/images/background/fire_cocktail.png
  client/src/components/Header/HeaderModal.js
  client/src/components/ImageUpload.js
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Input/CustomInput.js
  client/src/components/Input/GenderRadioInput.js
  client/src/components/Input/Input.js
  client/src/components/Input/SelectBaseInput.js
  client/src/components/Validation/CocktailFormValidation.js
  client/src/components/Validation/SignupValidation.js
  client/src/pages/CocktailForm.js
  client/src/pages/Signup.js
Labels: FE, Feat

#147 Fix/fe/bookmark
  client/src/components/BookmarkButton/BookmarkBtn.js
  client/src/components/BookmarkButton/BookmarkButton.js
  client/src/components/Card/Card.js
  client/src/pages/Category/Category.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/Recommend.js
  client/src/redux/slice/userInfoSlice.js
Labels: FE, Fix, 상

#148 Feat/fe/signup
  client/src/App.js
  client/src/components/Input/CustomInput.js
  client/src/components/Input/GenderRadioInput.js
  client/src/pages/Signup/Signup.js
Labels: FE, Feat, 상

#150 feat: 유저페이지 1차 완성
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/Swiper.css
  client/src/pages/UserPage/UserBookmarked.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserRecipe.js
Labels: FE, 상

#151 Feat/fe/login
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Signup/Signup.js
  client/src/redux/slice/userInfoSlice.js
Labels: FE, Feat, 상

#152 Fixed/fe/signup
  client/src/components/Header/Header.js
  client/src/components/Input/GenderRadioInput.js
  client/src/pages/Signup/Signup.js
Labels: FE, Fix

#153 fixed : 인풋창 패딩값 적용, 회원가입 인풋창 모바일 크기 변경
  client/src/components/Input/CustomInput.js
  client/src/pages/Signup/Signup.js
Labels: FE, Fix

#154 fixed : signup css 변경
  client/src/pages/Signup/Signup.js
Labels: FE, Fix

#155 feat : 헤더 햄버거 로그인시 카테고리 페이지 이동 버튼 생성
  client/src/components/Header/Hamburger.js
Labels: FE, Feat

#157 feat: 유저페이지 1차 완성
  client/public/images/user/user_admin.png
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/UserBookmarked.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserRecipe.js
Labels: FE, 상

#164 feat : 칵테일 유저 레시피 등록칸 제작
  client/src/components/Input/CocktailRecipeInput.js
  client/src/pages/CocktailForm.js
Labels: FE, Feat

#168 Feat/fe/cocktailform
  client/src/common/Buttons/HoverButton.js
  client/src/components/ImageUpload.js
  client/src/components/Input/CocktailRecipeInput.js
  client/src/components/Validation/CocktailFormValidation.js
  client/src/pages/CocktailForm.js
Labels: FE, Feat

#170 refactor: 주소 확인 코드 수정
  client/src/App.js
Labels: FE

#172 Feat/fe/cocktailform
  client/src/App.js
  client/src/common/Buttons/TagButton.js
  client/src/components/ImageUpload.js
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Validation/CocktailFormValidation.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailTag.js
Labels: FE, Feat, 상

#173 chore : tailwind 색상 추가 및 색상 변수 적용
  client/src/components/ImageUpload.js
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Input/CocktailRecipeInput.js
  client/src/components/Input/CustomInput.js
  client/src/components/Input/GenderRadioInput.js
  client/src/components/Input/SelectBaseInput.js
  client/tailwind.config.js
Labels: FE, Chore

#175 fixed : 이미지 업로드 fetch 키값 변경
  client/src/components/ImageUpload.js
Labels: FE, Fix

#177 fixed : 헤더 랜덤페이지 기본틀 완성 및 로고 경로 문제 이슈 해결
  client/src/components/Footer.js
  client/src/components/Header/Header.js
Labels: FE, Fix

#178 feat : 페이지 전환, 스크롤 맨위로
  client/src/common/ScrollTop.js
  client/src/index.js
Labels: FE, Feat

#180 fixed : 유효성 검사 데이터 흐름 오류 수정
  client/src/components/Header/HeaderModal.js
  client/src/components/Validation/CocktailFormValidation.js
  client/src/components/Validation/LoginValidation.js
  client/src/components/Validation/SignupValidation.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/Signup/Signup.js
Labels: FE, Fix

#181 fixed : userinfo 추가
  client/src/pages/Signup/Signup.js
Labels: FE, Fix

#182 fixed : 초기값이 true, 처음submit 버튼을 눌러도 유효성 검사 작동
  client/src/components/Header/HeaderModal.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/Signup/Signup.js
Labels: FE, Fix

#183 랜덤 페이지 get 요청
  client/src/components/Header/Header.js
Labels: FE, Feat

#184 fixed : imageupload가 실패해도 이미지 제목이 남아있던 버그 수정
  client/src/components/ImageUpload.js
Labels: FE, Fix

#185 Feat/fe/commentedit
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Comment/CommentPage.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/Signup/Signup.js
  client/src/redux/slice/isLoginSlice.js
  client/src/redux/slice/userInfoSlice.js
Labels: FE, Feat

#186 fixed : api 명세서에 따라 유저 칵테일 레시피 등록 변수명 수정
  client/src/components/ImageUpload.js
  client/src/components/Input/SelectBaseInput.js
  client/src/components/Validation/CocktailFormValidation.js
  client/src/pages/CocktailForm/CocktailForm.js
Labels: FE, Fix

#187 refactor : 사진 webp로 수정
  client/public/images/cocktailSample.jpg
  client/public/images/cocktailSample.webp
  client/public/images/fire.png
  client/public/images/fire.webp
  client/public/images/glass.svg
  client/public/images/logo.png
  client/public/images/logo.webp
  client/public/images/mainPromotion.png
  client/public/images/mainPromotion.webp
  client/public/images/slideText.png
  client/public/images/slideimg.png
  client/public/images/slideimg.webp
  client/public/images/star.png
  client/public/images/star.webp
  client/public/images/star_selected.png
  client/public/images/star_selected.webp
  client/public/images/슬라이더샘플.jpg
  client/public/images/슬라이더샘플.webp
  client/public/images/슬라이더샘플2.jpg
  client/public/images/슬라이더샘플2.webp
  client/src/App.js
  client/src/components/Footer.js
  client/src/components/Header/Header.js
  client/src/pages/Comment/CommentPage.js
  client/src/pages/LostPage.js
  client/src/pages/Main/Advice/Advice.js
  client/src/pages/Main/Ranking/Ranking.js
  client/src/pages/Main/Slider/Slider.js
  client/src/pages/RecipeDetail/RecipeInfo.js
  client/src/pages/Signup/Signup.js
Labels: FE, Refactoring

#189 Feat/fe/category
  client/src/pages/Category/Category.js
Labels: FE, Feat

#190 feat : lazy, suspense 적용 / 초기 렌더링 속도 개선
  client/src/App.js
Labels: FE, Feat

#191 Refactor/fe/category
  client/src/components/FIlterUrl/Filterurl.js
  client/src/pages/Category/Category.js
  client/src/pages/Category/CategoryBtn.js
  client/src/pages/Category/Filter.js
  client/src/pages/Category/Sort.js
  client/src/pages/Category/SortConditionButton.js
  client/src/pages/Category/TagFrequencyButton.js
Labels: FE, Refactoring

#192 fixed : 슬라이더 순서 변경, 루프 형태, 화살표 크기 반응형
  client/src/pages/Main/Slider/Slider.css
  client/src/pages/Main/Slider/Slider.js
Labels: FE, Fix

#194 Refactor/fe/filterinit
  client/src/components/FIlterUrl/Filterurl.js
  client/src/pages/Category/Category.js
Labels: FE, Refactoring

#196 feat : 랭킹카드 컴포넌트 분리, 리팩토링, 테두리 스타일 추가, 호버링 추가
  client/src/pages/Main/Ranking/Ranking.js
  client/src/pages/Main/Ranking/RankingCard.css
  client/src/pages/Main/Ranking/RankingCard.js
Labels: FE, Feat, Refactoring

#197 Fix/fe/category
  client/src/common/Data/index.js
  client/src/pages/Category/Category.js
Labels: FE, Fix

#199 Feat/fe/errormsg
  client/src/components/Header/Hamburger.js
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Category/Category.js
  client/src/pages/Signup/Signup.js
Labels: FE, Feat

#200 fix: 헤더 푸터 public 이미지 오류
  client/src/components/Footer.js
  client/src/components/Header/Header.js
  client/src/pages/LostPage.js
  client/src/pages/UserPage/Subscribe.js
Labels: FE, Fix

#201 Feat/fe/ranking
  client/src/pages/Main/Ranking/Ranking.js
  client/src/pages/Main/Ranking/RankingCard.js
Labels: FE, Feat

#202 feat: 상세페이지 api 연결
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/Process.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 중

#204 feat : 모킹 서버 데이터 구축
  client/package-lock.json
  client/package.json
  client/public/mockServiceWorker.js
  client/src/index.js
  client/src/mocks/browser.js
  client/src/mocks/handlers.js
Labels: FE, Feat

#206 Feat/fe/comment
  client/src/components/Header/HeaderModal.js
  client/src/index.js
  client/src/pages/Category/Category.js
  client/src/pages/Comment/CommentPage.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/redux/slice/userInfoSlice.js
Labels: FE, Feat

#207 Feat/fe/advice
  client/src/components/Header/HeaderModal.js
  client/src/index.js
  client/src/pages/Main/Advice/Advice.js
  client/src/redux/index.js
  client/src/redux/slice/isModalSlice.js
Labels: FE, Feat

#208 Feat/fe/mock
  client/src/mocks/handlers.js
  client/src/pages/CocktailForm/CocktailForm.js
Labels: FE, Feat

#211 feat: userpage api 연동, 비밀번호 모달 추가
  client/src/components/Validation/ModifyPwdValidation.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/UserPage/PasswordModal.js
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/Swiper.css
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserPageApi.js
Labels: FE, 상

#213 Fix/fe/login
  client/src/components/Card/Card.js
  client/src/pages/Category/Category.js
  client/src/pages/Signup/Signup.js
Labels: FE, Feat

#215 Fix/fe/bookmark
  client/src/components/Card/Card.js
Labels: FE, Fix

#216 Feat/fe/success
  client/package-lock.json
  client/package.json
  client/public/images/wave.svg
  client/src/App.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/Success/SuccessPage.css
  client/src/pages/Success/SuccessPage.js
Labels: FE, Feat

#217 chore : 사진 모서리 퐉 둥글게 했음
  client/src/pages/Success/SuccessPage.js
Labels: FE, Feat

#218 Fix/fe/login
  client/src/App.js
Labels: FE, Fix

#219 fixed : app.js navigate가 정의 되지않았던 문제 수정
  client/src/App.js
Labels: FE, Fix

#220 feat : 자신이 올린 칵테일 레시피 이동 구현
  client/src/pages/Success/SuccessPage.js
Labels: FE, Feat

#221 fixed : 이미지가 이상하게 구겨지던 현상 수정
  client/src/pages/Main/Ranking/Ranking.js
  client/src/pages/Main/Ranking/RankingCard.js
Labels: FE, Fix

#222 feat : 권유 컴포넌트 이미지 변경, 서버 에러시 이미지 변경
  client/public/images/errorPromotion.png
  client/public/images/mainPromotion.png
  client/src/pages/Main/Advice/Advice.js
  client/src/pages/Main/Main.js
  client/src/pages/Main/Ranking/Ranking.js
Labels: FE, Feat

#224 Chore/fe/cocktailform
  client/public/images/dnd.svg
  client/src/components/ImageUpload.js
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Input/CocktailRecipeInput.js
  client/src/components/Input/CustomInput.js
  client/src/components/Input/SelectBaseInput.js
  client/src/pages/CocktailForm/CocktailForm.js
Labels: FE, Chore

#225 chore : 푸터 텍스트 투명하게
  client/src/components/Footer.js
Labels: FE, Chore

#226 feat: 상세페이지 2차 완료
  client/public/images/btn_cu.webp
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/ImgaeModal.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 상

#227 feat: 유저페이지 자신의 레시피 카드 수정
  client/src/components/Card/OwnRecipeCard.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserRecipe.js
Labels: FE, 중

#228 Fix/fe/bookmarked
  client/package-lock.json
  client/package.json
  client/src/components/Card/Card.js
  client/src/components/Header/Hamburger.js
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Category/Category.js
  client/src/redux/slice/userInfoSlice.js
Labels: FE, Fix

#229 Feat/fe/userpage
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 상

#231 feat: api 명세서 수정사항 적용
  client/src/pages/UserPage/UserBookmarked.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserRecipe.js
Labels: FE, 중

#232 chore: 상세페이지 이미지와 모달 사이즈 수정
  client/src/pages/RecipeDetail/ImgaeModal.js
Labels: FE, 하

#233 Feat/fe/bookmarkdetail
  client/src/pages/RecipeDetail/RecipeDetail.js
Labels: FE, Feat

#234 Chore/fe/swiper
  client/public/images/drinkers.png
  client/public/images/mainPromotion.webp
  client/public/images/swiper/chat.png
  client/public/images/swiper/filter.png
  client/public/images/swiper/recipe.png
  client/public/images/swiper/slideimg.webp
  client/public/images/swiper/슬라이더샘플.webp
  client/public/images/swiper/슬라이더샘플2.webp
  client/src/pages/Main/Slider/Slider.js
Labels: FE, Chore

#235 Feat/fe/bookmarkdetail
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
Labels: FE, Feat

#236 fixed : 상세 페이지 들어갔을때 추천 탭 강조 삭제, 호버링시 글자색 무지개로 변경
  client/src/components/Header/Header.js
Labels: FE, Fix

#237 feat: 상세페이지 api 연결 추가
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/ImgaeModal.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
  client/src/pages/RecipeDetail/Recommend.js
Labels: FE, 상

#238 Fix/fe/comment
  client/src/components/Validation/CommentValidation.js
  client/src/pages/Comment/CommentPage.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
Labels: FE, Fix

#239 feat: 별점 api 연결
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 중

#240 feat : 메인페이지 슬라이더 이미지 수정
  client/public/images/swiper/슬라이더샘플3.png
  client/src/pages/Main/Slider/Slider.js
Labels: FE, Feat

#241 Fixed/fe/userid
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/UserPage/PasswordModal.js
  client/src/redux/slice/userInfoSlice.js
Labels: FE, Fix

#243 feat: fadein 애니메이션 추가
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
  client/tailwind.config.js
Labels: FE, 하

#242 feat : 로딩 컴포넌트 구현
  client/public/images/loading/loading.svg
  client/public/images/loading/loading2.svg
  client/public/images/loading/loading3.svg
  client/src/App.js
  client/src/components/Loading.js
Labels: FE, Feat

#244 Fix/fe/bookmark
  client/src/components/BookmarkButton/BookmarkBtn.js
  client/src/components/BookmarkButton/BookmarkButton.js
  client/src/components/Card/Card.js
  client/src/pages/RecipeDetail/RecipeDetail.js
Labels: FE, Fix

#245 feat: 유저페이지 비밀번호 수정과 회원탈퇴 기능 추가
  client/src/pages/UserPage/PasswordModal.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserPageApi.js
Labels: FE, 중

#248 fixed : 린트 룰 추가
  client/.eslintrc.json
Labels: FE, Fix

#250 feat : 칵테일 등록 페이지, 칵테일 등록 성공 페이지 로딩창 적용
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/Success/SuccessPage.js
Labels: FE, Feat

#252 Feat/fe/cocktailmodifiy
  client/src/App.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, Feat

#256 feat: SNS 메타태그 설정
  client/public/images/logo_metatag.webp
  client/public/index.html
Labels: FE, 하

#258 Fix/fe/login
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Category/Category.js
Labels: FE, Fix

#259 fix: 상세페이지 로그인 여부 로직 변경
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 상

#260 fixed : 이미지 사이즈 문제 해결
  client/src/pages/Main/Advice/Advice.js
  client/src/pages/Main/Ranking/RankingCard.js
  client/src/pages/Success/SuccessPage.js
Labels: FE, Fix

#262 Fix/fe/login
  client/src/App.js
  client/src/components/Card/Card.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Category/Category.js
  client/src/pages/Category/Filter.js
  client/src/pages/Comment/CommentPage.js
  client/src/pages/RecipeDetail/Recommend.js
Labels: FE, Fix

#263 feat: localStorage 데이터 연결
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 중

#264 Chore/fe/category
  client/public/images/arrow/arrowDownOff.png
  client/public/images/arrow/arrowDownOn.png
  client/public/images/arrow/arrowUpOff.png
  client/public/images/arrow/arrowUpOn.png
  client/src/components/Header/HeaderModal.js
  client/src/pages/Category/Sort.js
Labels: FE, Chore

#265 feat: 상세페이지 관리자 페이지 접근 불가
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 중

#268 Feat/fe/cocktailmodify
  client/src/components/ImageUpload.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/CocktailForm/TransformData.js
Labels: FE, Feat

#269 Dev/fe
  client/src/components/Card/OwnRecipeCard.js
  client/src/components/ImageUpload.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/CocktailForm/TransformData.js
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/Swiper.css
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserPageApi.js
  client/src/pages/UserPage/UserRecipe.js
Labels: FE, Feat, Fix, 상, Chore

#273 Fixed/fe/swiper
  client/src/pages/Main/Slider/Slider.js
  client/tailwind.config.js
Labels: FE, Fix, Chore

#272 refactor: 상세페이지 불필요한 코드 제거
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
  client/src/pages/RecipeDetail/Recommend.js
Labels: FE

#274 Fix/fe/login
  .DS_Store
  client/public/index.html
  client/src/api/api.js
  client/src/components/Card/Card.js
  client/src/components/Header/Header.js
  client/src/pages/Category/Category.js
  client/src/pages/Category/Filter.js
  client/src/pages/Main/Ranking/Ranking.js
  client/src/service/index.js
Labels: FE, Fix

#279 feat: 슬라이더 무한 루프 구현
  client/src/components/Card/OwnRecipeCard.js
  client/src/pages/UserPage/PasswordModal.js
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/Swiper.css
  client/src/pages/UserPage/UserBookmarked.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserRecipe.js
Labels: FE

#283 feat : 칵테일 속재료 로직 분리
  client/src/components/Input/AddIngreInput.js
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Validation/CocktailFormValidation.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/CocktailForm/TransformData.js
Labels: FE, Feat, Fix

#285 Refactor/fe/api
  client/src/api/api.js
  client/src/components/Header/Hamburger.js
  client/src/components/Header/Header.js
  client/src/hook/useLogout.js
  client/src/pages/Signup/Signup.js
  client/src/service/index.js
Labels: FE, Refactoring

#286 Feat/fe/cocktailform
  client/src/components/Input/AddIngreInput.js
  client/src/pages/CocktailForm/CocktailForm.js
Labels: FE, Feat, 상

#288 Refactor/fe/api
  client/public/images/delete/x.png
  client/src/api/api.js
  client/src/components/Card/Card.js
  client/src/components/Header/HeaderModal.js
  client/src/pages/Category/Category.js
  client/src/pages/Signup/Signup.js
Labels: FE, Refactoring

#289 feat: 상세페이지 탈퇴여부 확인
  client/src/components/Validation/CommentValidation.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/ImgaeModal.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 상

#291 Feat/fe/cocktailmodify
  client/src/components/Input/AddIngreInput.js
  client/src/components/Validation/CocktailFormValidation.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/CocktailForm/TransformData.js
Labels: FE, Feat

#292 Refactor/fe/api
  client/src/api/CocktailFormApi.js
  client/src/api/RankingApi.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/Main/Ranking/Ranking.js
Labels: FE, Refactoring

#293 배포_0.4ver
  .DS_Store
  client/public/images/delete/x.png
  client/public/index.html
  client/src/api/CocktailFormApi.js
  client/src/api/RankingApi.js
  client/src/api/api.js
  client/src/components/Card/Card.js
  client/src/components/Card/OwnRecipeCard.js
  client/src/components/Header/Hamburger.js
  client/src/components/Header/Header.js
  client/src/components/Header/HeaderModal.js
  client/src/components/Input/AddIngreInput.js
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Validation/CommentValidation.js
  client/src/hook/useLogout.js
  client/src/pages/Category/Category.js
  client/src/pages/Category/Filter.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/CocktailForm/TransformData.js
  client/src/pages/Main/Ranking/Ranking.js
  client/src/pages/Main/Slider/Slider.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/ImgaeModal.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
  client/src/pages/RecipeDetail/Recommend.js
  client/src/pages/Signup/Signup.js
  client/src/pages/UserPage/PasswordModal.js
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/Swiper.css
  client/src/pages/UserPage/UserBookmarked.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserRecipe.js
  client/src/service/index.js
  client/tailwind.config.js
Labels: FE, Feat, Fix, Refactoring, 상, Chore

#294 Refactor/fe/userinfo
  client/src/api/api.js
  client/src/components/Header/HeaderModal.js
Labels: FE, Refactoring

#295 refact: 필터 코드분리
  client/src/api/api.js
  client/src/pages/Category/Category.js
Labels: FE, Refactoring

#296 feat : 베이스 술 종류 추가 및 불필요한 함수 및 변수 제거
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Input/SelectBaseInput.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
Labels: FE, Fix, Refactoring

#297 feat : 베이스 술 한영 변환 로직 추가 & 막걸리 추가
  client/src/components/Input/SelectBaseInput.js
  client/src/pages/CocktailForm/TransformData.js
Labels: FE, Feat, Fix

#299 fix: accessToken 첫 사용시 안되는 버그 해결
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeApi.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 상

#300 fix: accessToken 첫 사용시 오류 수정
  client/src/pages/UserPage/PasswordModal.js
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserPageApi.js
Labels: FE, 상

#301 fix: 유저페이지 accessToken 첫 사용시 오류 해결
  client/src/pages/UserPage/UserInfo.js
Labels: FE, 상

#303 fix: api 통신 이전에 새로고침되는 오류 해결
  client/src/api/RecipeApi.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, 상

#304 feat: 상세페이지 답변 선택 시 댓글창으로 스크롤 이동 기능 추가
  client/src/pages/RecipeDetail/Community.js
Labels: FE

#305 Refactor/fe/comment
  client/src/api/api.js
  client/src/pages/Comment/CommentPage.js
Labels: FE, Refactoring

#306 Refactor/fe/cocktailpost
  client/src/api/CocktailFormApi.js
  client/src/api/api.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/Comment/CommentPage.js
Labels: FE, Feat, Refactoring

#307 chore: 카테고리와 태그 버튼 스타일 수정
  client/src/common/Data/index.js
  client/src/pages/Category/CategoryBtn.js
  client/src/pages/Category/Filter.js
  client/src/pages/Category/TagFrequencyButton.js
Labels: FE

#308 배포_0.6ver
  client/src/api/CocktailFormApi.js
  client/src/api/RecipeApi.js
  client/src/api/api.js
  client/src/common/Data/index.js
  client/src/components/Header/HeaderModal.js
  client/src/components/Input/CheckboxIngrInput.js
  client/src/components/Input/SelectBaseInput.js
  client/src/pages/Category/Category.js
  client/src/pages/Category/CategoryBtn.js
  client/src/pages/Category/Filter.js
  client/src/pages/Category/TagFrequencyButton.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/CocktailForm/TransformData.js
  client/src/pages/Comment/CommentPage.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
  client/src/pages/UserPage/PasswordModal.js
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
  client/src/pages/UserPage/UserPageApi.js
Labels: FE, Feat, Fix, Refactoring, 상, Chore

#310 feat : 배포 환경 리다이렉트 설정
  client/public/_redirects
Labels: FE, Feat

#312 fix: accessToken 이슈 해결
  client/src/api/RecipeApi.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE

#313 fix: localStorage 에서 accessToken 획득 에러 해결
  client/src/api/UserPageApi.js
  client/src/pages/UserPage/PasswordModal.js
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
Labels: FE

#314 Refactor/fe/star
  client/src/api/CocktailFormApi.js
  client/src/api/RecipeApi.js
  client/src/api/api.js
  client/src/common/Data/index.js
  client/src/components/ImageUpload.js
  client/src/pages/Category/Category.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/Comment/CommentPage.js
Labels: FE, Fix

#316 chore : 슬라이더 이미지 수정, 반응형 수정
  client/src/pages/Main/Slider/Slider.js
Labels: FE, Feat

#317 feat : 푸터에 해당하는 섹션 클릭시 경로 이동
  client/src/components/Footer.js
Labels: FE, Feat

#320 fix: 대댓글 api
  client/src/pages/Comment/CommentPage.js
Labels: FE, Fix

#322 feat: 날라간 데이터 수정
  client/src/pages/Comment/CommentPage.js
Labels: FE, Fix

#323 Fix/fe/cocktailform
  client/src/api/CocktailFormApi.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
Labels: FE, Fix

#324 Chore/fe/mainpage
  client/src/pages/Main/Advice/Advice.js
  client/src/pages/Main/Slider/Slider.js
Labels: FE, Chore

#330 배포_0.6ver
  client/src/api/CocktailFormApi.js
  client/src/api/RankingApi.js
  client/src/api/RecipeApi.js
  client/src/api/api.js
  client/src/hook/useLogout.js
  client/src/pages/Category/Category.js
  client/src/pages/CocktailForm/CocktailForm.js
  client/src/pages/CocktailForm/CocktailModifyForm.js
  client/src/pages/Comment/CommentPage.js
  client/src/pages/Main/Advice/Advice.js
  client/src/pages/Main/Ranking/Ranking.js
  client/src/pages/Main/Slider/Slider.js
  client/src/pages/RecipeDetail/Community.js
  client/src/pages/RecipeDetail/RecipeDetail.js
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE, Feat, Fix, Refactoring, Chore

#331 fix: 회원정보조회/수정/탈퇴/구독생성/취소
  client/src/api/UserPageApi.js
Labels: FE, Fix, Refactoring

#333 fixed : 맛 태그 버튼 색깔이 안바뀌던 문제 해결
  client/src/common/Buttons/FlavorButton.js
  client/src/pages/CocktailForm/CocktailTag.js
Labels: FE, Fix

#332 fix: 페이지네이션 구현 완료
  client/src/components/Card/SkeletonCard.js
  client/src/components/Pagination/Pagination2.js
  client/src/pages/Category/Category.js
  client/tailwind.config.js
Labels: FE

#335 fix: 구독 삭제 오류 해결
  client/src/pages/UserPage/Subscribe.js
  client/src/pages/UserPage/UserInfo.js
  client/src/pages/UserPage/UserPage.js
Labels: FE

#337 chore: 관리자 id 변경
  client/src/pages/RecipeDetail/RecipeInfo.js
Labels: FE
