Repository codestates-seb/seb44_main_002, pull requests merged in 2023-08, with the labels that each got.

#450 fix: 글자와 이미지 깨짐 현상 수정
  client/src/components/Card/OwnRecipeCard.js
  client/src/pages/UserPage/UserInfo.js
Labels: FE, Fix

#451 프로젝트 보수작업 진행
  client/src/components/Card/OwnRecipeCard.js
  client/src/components/Header/Header.js
  client/src/pages/UserPage/UserInfo.js
Labels: FE, Fix, Refactoring, Chore

#452 Release
  client/src/components/Card/OwnRecipeCard.js
  client/src/components/Header/Header.js
  client/src/pages/UserPage/UserInfo.js
Labels: FE
